DefaultContentLanguage: en
baseURL: https://68Keys.io/
title: Custom 68% Mechanical Keyboard - 68Keys.io

disableHugoGeneratorInject: true
disableRSS: true
disable404: true

enableRobotsTXT: true

taxonomies:
  tag: ''
  category: ''
